repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.0
    hooks:
      - id: pylint
        additional_dependencies: [fastapi, uvicorn, psycopg2-binary, pandas, requests, python-dotenv, pydantic, sqlalchemy, apache-airflow]
