blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/willhuntleyclarke/ticker-converter/blob/main/README.md
    about: Check the project documentation first
  - name: Discussions
    url: https://github.com/willhuntleyclarke/ticker-converter/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issues
    url: https://github.com/willhuntleyclarke/ticker-converter/security/advisories/new
    about: Report security vulnerabilities privately
